-- Migration 074: Exercise catalog seed (global library)
-- Companion to 073_exercise_logging.sql. Seeds a curated static list of ~180 common
-- movements into the `exercises` catalog as GLOBAL library rows
-- (is_custom = false, is_public = true, created_by = NULL).
--
-- Coverage: chest / back / legs (quads, hamstrings, glutes, calves) / shoulders /
-- biceps / triceps / forearms / core / full-body & olympic, across barbell, dumbbell,
-- machine, cable, bodyweight, kettlebell, band and "other" equipment, plus a few
-- cardio-machine entries (distance_duration / duration tracking).
--
-- Idempotent: guarded so re-running does not duplicate the global seed.

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM exercises WHERE is_custom = false AND name = 'Barbell Bench Press'
  ) THEN

INSERT INTO exercises (name, primary_muscle, secondary_muscles, equipment, movement, tracking_type) VALUES
  ('Barbell Bench Press', 'chest', '{"triceps","shoulders"}', 'barbell', 'push', 'weight_reps'),
  ('Incline Barbell Bench Press', 'chest', '{"shoulders","triceps"}', 'barbell', 'push', 'weight_reps'),
  ('Decline Barbell Bench Press', 'chest', '{"triceps"}', 'barbell', 'push', 'weight_reps'),
  ('Dumbbell Bench Press', 'chest', '{"triceps","shoulders"}', 'dumbbell', 'push', 'weight_reps'),
  ('Incline Dumbbell Press', 'chest', '{"shoulders","triceps"}', 'dumbbell', 'push', 'weight_reps'),
  ('Decline Dumbbell Press', 'chest', '{"triceps"}', 'dumbbell', 'push', 'weight_reps'),
  ('Dumbbell Fly', 'chest', '{"shoulders"}', 'dumbbell', 'isolation', 'weight_reps'),
  ('Incline Dumbbell Fly', 'chest', '{"shoulders"}', 'dumbbell', 'isolation', 'weight_reps'),
  ('Cable Fly', 'chest', '{"shoulders"}', 'cable', 'isolation', 'weight_reps'),
  ('Low Cable Fly', 'chest', '{"shoulders"}', 'cable', 'isolation', 'weight_reps'),
  ('High Cable Fly', 'chest', '{"shoulders"}', 'cable', 'isolation', 'weight_reps'),
  ('Machine Chest Press', 'chest', '{"triceps","shoulders"}', 'machine', 'push', 'weight_reps'),
  ('Incline Machine Chest Press', 'chest', '{"shoulders","triceps"}', 'machine', 'push', 'weight_reps'),
  ('Pec Deck Machine', 'chest', '{"shoulders"}', 'machine', 'isolation', 'weight_reps'),
  ('Smith Machine Bench Press', 'chest', '{"triceps","shoulders"}', 'machine', 'push', 'weight_reps'),
  ('Push-Up', 'chest', '{"triceps","shoulders","core"}', 'bodyweight', 'push', 'reps_only'),
  ('Incline Push-Up', 'chest', '{"triceps","shoulders"}', 'bodyweight', 'push', 'reps_only'),
  ('Decline Push-Up', 'chest', '{"shoulders","triceps"}', 'bodyweight', 'push', 'reps_only'),
  ('Chest Dip', 'chest', '{"triceps","shoulders"}', 'bodyweight', 'push', 'reps_only'),
  ('Deadlift', 'back', '{"glutes","hamstrings","core"}', 'barbell', 'hinge', 'weight_reps'),
  ('Conventional Deadlift', 'back', '{"glutes","hamstrings","core"}', 'barbell', 'hinge', 'weight_reps'),
  ('Sumo Deadlift', 'back', '{"glutes","hamstrings","quads"}', 'barbell', 'hinge', 'weight_reps'),
  ('Romanian Deadlift', 'hamstrings', '{"glutes","back"}', 'barbell', 'hinge', 'weight_reps'),
  ('Barbell Row', 'back', '{"biceps","shoulders"}', 'barbell', 'pull', 'weight_reps'),
  ('Bent-Over Barbell Row', 'back', '{"biceps","shoulders"}', 'barbell', 'pull', 'weight_reps'),
  ('Pendlay Row', 'back', '{"biceps","shoulders"}', 'barbell', 'pull', 'weight_reps'),
  ('T-Bar Row', 'back', '{"biceps","shoulders"}', 'barbell', 'pull', 'weight_reps'),
  ('Dumbbell Row', 'back', '{"biceps","shoulders"}', 'dumbbell', 'pull', 'weight_reps'),
  ('Single-Arm Dumbbell Row', 'back', '{"biceps","shoulders"}', 'dumbbell', 'pull', 'weight_reps'),
  ('Chest-Supported Dumbbell Row', 'back', '{"biceps","shoulders"}', 'dumbbell', 'pull', 'weight_reps'),
  ('Seated Cable Row', 'back', '{"biceps","shoulders"}', 'cable', 'pull', 'weight_reps'),
  ('Wide-Grip Seated Cable Row', 'back', '{"biceps","shoulders"}', 'cable', 'pull', 'weight_reps'),
  ('Lat Pulldown', 'back', '{"biceps"}', 'cable', 'pull', 'weight_reps'),
  ('Wide-Grip Lat Pulldown', 'back', '{"biceps"}', 'cable', 'pull', 'weight_reps'),
  ('Close-Grip Lat Pulldown', 'back', '{"biceps"}', 'cable', 'pull', 'weight_reps'),
  ('Straight-Arm Pulldown', 'back', '{"triceps"}', 'cable', 'isolation', 'weight_reps'),
  ('Pull-Up', 'back', '{"biceps","shoulders"}', 'bodyweight', 'pull', 'reps_only'),
  ('Chin-Up', 'back', '{"biceps"}', 'bodyweight', 'pull', 'reps_only'),
  ('Neutral-Grip Pull-Up', 'back', '{"biceps"}', 'bodyweight', 'pull', 'reps_only'),
  ('Machine Row', 'back', '{"biceps","shoulders"}', 'machine', 'pull', 'weight_reps'),
  ('Machine Lat Pulldown', 'back', '{"biceps"}', 'machine', 'pull', 'weight_reps'),
  ('Inverted Row', 'back', '{"biceps","shoulders"}', 'bodyweight', 'pull', 'reps_only'),
  ('Face Pull', 'shoulders', '{"back"}', 'cable', 'pull', 'weight_reps'),
  ('Back Extension', 'back', '{"glutes","hamstrings"}', 'bodyweight', 'hinge', 'reps_only'),
  ('Rack Pull', 'back', '{"glutes","hamstrings"}', 'barbell', 'hinge', 'weight_reps'),
  ('Barbell Shrug', 'back', '{"shoulders"}', 'barbell', 'isolation', 'weight_reps'),
  ('Dumbbell Shrug', 'back', '{"shoulders"}', 'dumbbell', 'isolation', 'weight_reps'),
  ('Barbell Back Squat', 'quads', '{"glutes","hamstrings","core"}', 'barbell', 'squat', 'weight_reps'),
  ('Barbell Front Squat', 'quads', '{"glutes","core"}', 'barbell', 'squat', 'weight_reps'),
  ('High-Bar Back Squat', 'quads', '{"glutes","hamstrings"}', 'barbell', 'squat', 'weight_reps'),
  ('Low-Bar Back Squat', 'quads', '{"glutes","hamstrings"}', 'barbell', 'squat', 'weight_reps'),
  ('Goblet Squat', 'quads', '{"glutes","core"}', 'dumbbell', 'squat', 'weight_reps'),
  ('Hack Squat', 'quads', '{"glutes"}', 'machine', 'squat', 'weight_reps'),
  ('Leg Press', 'quads', '{"glutes","hamstrings"}', 'machine', 'squat', 'weight_reps'),
  ('Bulgarian Split Squat', 'quads', '{"glutes","hamstrings"}', 'dumbbell', 'squat', 'weight_reps'),
  ('Walking Lunge', 'quads', '{"glutes","hamstrings"}', 'dumbbell', 'squat', 'weight_reps'),
  ('Dumbbell Lunge', 'quads', '{"glutes","hamstrings"}', 'dumbbell', 'squat', 'weight_reps'),
  ('Barbell Lunge', 'quads', '{"glutes","hamstrings"}', 'barbell', 'squat', 'weight_reps'),
  ('Reverse Lunge', 'quads', '{"glutes","hamstrings"}', 'dumbbell', 'squat', 'weight_reps'),
  ('Step-Up', 'quads', '{"glutes"}', 'dumbbell', 'squat', 'weight_reps'),
  ('Leg Extension', 'quads', '{}', 'machine', 'isolation', 'weight_reps'),
  ('Leg Curl', 'hamstrings', '{}', 'machine', 'isolation', 'weight_reps'),
  ('Seated Leg Curl', 'hamstrings', '{}', 'machine', 'isolation', 'weight_reps'),
  ('Lying Leg Curl', 'hamstrings', '{}', 'machine', 'isolation', 'weight_reps'),
  ('Stiff-Leg Deadlift', 'hamstrings', '{"glutes","back"}', 'barbell', 'hinge', 'weight_reps'),
  ('Good Morning', 'hamstrings', '{"glutes","back"}', 'barbell', 'hinge', 'weight_reps'),
  ('Hip Thrust', 'glutes', '{"hamstrings"}', 'barbell', 'hinge', 'weight_reps'),
  ('Barbell Hip Thrust', 'glutes', '{"hamstrings"}', 'barbell', 'hinge', 'weight_reps'),
  ('Glute Bridge', 'glutes', '{"hamstrings"}', 'bodyweight', 'hinge', 'reps_only'),
  ('Cable Pull-Through', 'glutes', '{"hamstrings"}', 'cable', 'hinge', 'weight_reps'),
  ('Standing Calf Raise', 'calves', '{}', 'machine', 'isolation', 'weight_reps'),
  ('Seated Calf Raise', 'calves', '{}', 'machine', 'isolation', 'weight_reps'),
  ('Dumbbell Calf Raise', 'calves', '{}', 'dumbbell', 'isolation', 'weight_reps'),
  ('Smith Machine Calf Raise', 'calves', '{}', 'machine', 'isolation', 'weight_reps'),
  ('Pistol Squat', 'quads', '{"glutes","core"}', 'bodyweight', 'squat', 'reps_only'),
  ('Bodyweight Squat', 'quads', '{"glutes"}', 'bodyweight', 'squat', 'reps_only'),
  ('Sissy Squat', 'quads', '{}', 'bodyweight', 'squat', 'reps_only'),
  ('Hip Adduction Machine', 'quads', '{}', 'machine', 'isolation', 'weight_reps'),
  ('Hip Abduction Machine', 'glutes', '{}', 'machine', 'isolation', 'weight_reps'),
  ('Nordic Hamstring Curl', 'hamstrings', '{}', 'bodyweight', 'isolation', 'reps_only'),
  ('Overhead Press', 'shoulders', '{"triceps","core"}', 'barbell', 'push', 'weight_reps'),
  ('Standing Barbell Overhead Press', 'shoulders', '{"triceps","core"}', 'barbell', 'push', 'weight_reps'),
  ('Seated Barbell Overhead Press', 'shoulders', '{"triceps"}', 'barbell', 'push', 'weight_reps'),
  ('Dumbbell Shoulder Press', 'shoulders', '{"triceps"}', 'dumbbell', 'push', 'weight_reps'),
  ('Seated Dumbbell Shoulder Press', 'shoulders', '{"triceps"}', 'dumbbell', 'push', 'weight_reps'),
  ('Arnold Press', 'shoulders', '{"triceps"}', 'dumbbell', 'push', 'weight_reps'),
  ('Machine Shoulder Press', 'shoulders', '{"triceps"}', 'machine', 'push', 'weight_reps'),
  ('Push Press', 'shoulders', '{"triceps","legs"}', 'barbell', 'push', 'weight_reps'),
  ('Dumbbell Lateral Raise', 'shoulders', '{}', 'dumbbell', 'isolation', 'weight_reps'),
  ('Cable Lateral Raise', 'shoulders', '{}', 'cable', 'isolation', 'weight_reps'),
  ('Machine Lateral Raise', 'shoulders', '{}', 'machine', 'isolation', 'weight_reps'),
  ('Dumbbell Front Raise', 'shoulders', '{}', 'dumbbell', 'isolation', 'weight_reps'),
  ('Cable Front Raise', 'shoulders', '{}', 'cable', 'isolation', 'weight_reps'),
  ('Dumbbell Rear Delt Fly', 'shoulders', '{"back"}', 'dumbbell', 'isolation', 'weight_reps'),
  ('Reverse Pec Deck', 'shoulders', '{"back"}', 'machine', 'isolation', 'weight_reps'),
  ('Upright Row', 'shoulders', '{"back"}', 'barbell', 'pull', 'weight_reps'),
  ('Cable Upright Row', 'shoulders', '{"back"}', 'cable', 'pull', 'weight_reps'),
  ('Landmine Press', 'shoulders', '{"triceps","chest"}', 'barbell', 'push', 'weight_reps'),
  ('Pike Push-Up', 'shoulders', '{"triceps"}', 'bodyweight', 'push', 'reps_only'),
  ('Handstand Push-Up', 'shoulders', '{"triceps"}', 'bodyweight', 'push', 'reps_only'),
  ('Barbell Curl', 'biceps', '{"forearms"}', 'barbell', 'isolation', 'weight_reps'),
  ('EZ-Bar Curl', 'biceps', '{"forearms"}', 'barbell', 'isolation', 'weight_reps'),
  ('Dumbbell Curl', 'biceps', '{"forearms"}', 'dumbbell', 'isolation', 'weight_reps'),
  ('Alternating Dumbbell Curl', 'biceps', '{"forearms"}', 'dumbbell', 'isolation', 'weight_reps'),
  ('Hammer Curl', 'biceps', '{"forearms"}', 'dumbbell', 'isolation', 'weight_reps'),
  ('Incline Dumbbell Curl', 'biceps', '{"forearms"}', 'dumbbell', 'isolation', 'weight_reps'),
  ('Concentration Curl', 'biceps', '{}', 'dumbbell', 'isolation', 'weight_reps'),
  ('Preacher Curl', 'biceps', '{}', 'barbell', 'isolation', 'weight_reps'),
  ('Machine Preacher Curl', 'biceps', '{}', 'machine', 'isolation', 'weight_reps'),
  ('Cable Curl', 'biceps', '{"forearms"}', 'cable', 'isolation', 'weight_reps'),
  ('Cable Rope Hammer Curl', 'biceps', '{"forearms"}', 'cable', 'isolation', 'weight_reps'),
  ('Spider Curl', 'biceps', '{}', 'dumbbell', 'isolation', 'weight_reps'),
  ('Chin-Up (Biceps Focus)', 'biceps', '{"back"}', 'bodyweight', 'pull', 'reps_only'),
  ('Close-Grip Bench Press', 'triceps', '{"chest","shoulders"}', 'barbell', 'push', 'weight_reps'),
  ('Triceps Pushdown', 'triceps', '{}', 'cable', 'isolation', 'weight_reps'),
  ('Rope Triceps Pushdown', 'triceps', '{}', 'cable', 'isolation', 'weight_reps'),
  ('Overhead Cable Triceps Extension', 'triceps', '{}', 'cable', 'isolation', 'weight_reps'),
  ('Overhead Dumbbell Triceps Extension', 'triceps', '{}', 'dumbbell', 'isolation', 'weight_reps'),
  ('Skull Crusher', 'triceps', '{}', 'barbell', 'isolation', 'weight_reps'),
  ('Dumbbell Skull Crusher', 'triceps', '{}', 'dumbbell', 'isolation', 'weight_reps'),
  ('Triceps Kickback', 'triceps', '{}', 'dumbbell', 'isolation', 'weight_reps'),
  ('Bench Dip', 'triceps', '{"chest","shoulders"}', 'bodyweight', 'push', 'reps_only'),
  ('Triceps Dip', 'triceps', '{"chest","shoulders"}', 'bodyweight', 'push', 'reps_only'),
  ('Diamond Push-Up', 'triceps', '{"chest"}', 'bodyweight', 'push', 'reps_only'),
  ('JM Press', 'triceps', '{"chest"}', 'barbell', 'push', 'weight_reps'),
  ('Barbell Wrist Curl', 'forearms', '{}', 'barbell', 'isolation', 'weight_reps'),
  ('Dumbbell Wrist Curl', 'forearms', '{}', 'dumbbell', 'isolation', 'weight_reps'),
  ('Reverse Wrist Curl', 'forearms', '{}', 'barbell', 'isolation', 'weight_reps'),
  ('Reverse Barbell Curl', 'forearms', '{"biceps"}', 'barbell', 'isolation', 'weight_reps'),
  ('Farmer''s Carry', 'forearms', '{"core","back"}', 'dumbbell', 'carry', 'weight_reps'),
  ('Dead Hang', 'forearms', '{"back"}', 'bodyweight', 'carry', 'duration'),
  ('Plank', 'core', '{"shoulders"}', 'bodyweight', 'core', 'duration'),
  ('Side Plank', 'core', '{}', 'bodyweight', 'core', 'duration'),
  ('Hanging Leg Raise', 'core', '{"forearms"}', 'bodyweight', 'core', 'reps_only'),
  ('Hanging Knee Raise', 'core', '{}', 'bodyweight', 'core', 'reps_only'),
  ('Captain''s Chair Leg Raise', 'core', '{}', 'machine', 'core', 'reps_only'),
  ('Crunch', 'core', '{}', 'bodyweight', 'core', 'reps_only'),
  ('Cable Crunch', 'core', '{}', 'cable', 'core', 'weight_reps'),
  ('Bicycle Crunch', 'core', '{}', 'bodyweight', 'core', 'reps_only'),
  ('Sit-Up', 'core', '{}', 'bodyweight', 'core', 'reps_only'),
  ('Russian Twist', 'core', '{}', 'bodyweight', 'core', 'reps_only'),
  ('Ab Wheel Rollout', 'core', '{"shoulders"}', 'other', 'core', 'reps_only'),
  ('Mountain Climber', 'core', '{"shoulders"}', 'bodyweight', 'core', 'reps_only'),
  ('Dead Bug', 'core', '{}', 'bodyweight', 'core', 'reps_only'),
  ('Hollow Body Hold', 'core', '{}', 'bodyweight', 'core', 'duration'),
  ('Leg Raise', 'core', '{}', 'bodyweight', 'core', 'reps_only'),
  ('Decline Sit-Up', 'core', '{}', 'bodyweight', 'core', 'reps_only'),
  ('Machine Ab Crunch', 'core', '{}', 'machine', 'core', 'weight_reps'),
  ('Pallof Press', 'core', '{}', 'cable', 'core', 'weight_reps'),
  ('Wood Chop', 'core', '{"shoulders"}', 'cable', 'core', 'weight_reps'),
  ('Power Clean', 'fullBody', '{"back","legs","shoulders"}', 'barbell', 'pull', 'weight_reps'),
  ('Hang Clean', 'fullBody', '{"back","legs","shoulders"}', 'barbell', 'pull', 'weight_reps'),
  ('Clean and Jerk', 'fullBody', '{"legs","shoulders","back"}', 'barbell', 'pull', 'weight_reps'),
  ('Snatch', 'fullBody', '{"legs","shoulders","back"}', 'barbell', 'pull', 'weight_reps'),
  ('Clean and Press', 'fullBody', '{"shoulders","legs","back"}', 'barbell', 'push', 'weight_reps'),
  ('Thruster', 'fullBody', '{"quads","shoulders"}', 'barbell', 'squat', 'weight_reps'),
  ('Dumbbell Thruster', 'fullBody', '{"quads","shoulders"}', 'dumbbell', 'squat', 'weight_reps'),
  ('Kettlebell Swing', 'glutes', '{"hamstrings","core","shoulders"}', 'kettlebell', 'hinge', 'weight_reps'),
  ('Kettlebell Goblet Squat', 'quads', '{"glutes","core"}', 'kettlebell', 'squat', 'weight_reps'),
  ('Kettlebell Clean', 'fullBody', '{"legs","shoulders"}', 'kettlebell', 'pull', 'weight_reps'),
  ('Kettlebell Snatch', 'fullBody', '{"legs","shoulders"}', 'kettlebell', 'pull', 'weight_reps'),
  ('Turkish Get-Up', 'fullBody', '{"core","shoulders"}', 'kettlebell', 'carry', 'weight_reps'),
  ('Burpee', 'fullBody', '{"chest","legs","core"}', 'bodyweight', 'squat', 'reps_only'),
  ('Box Jump', 'quads', '{"glutes","calves"}', 'bodyweight', 'squat', 'reps_only'),
  ('Wall Ball', 'fullBody', '{"quads","shoulders"}', 'other', 'squat', 'reps_only'),
  ('Battle Ropes', 'fullBody', '{"shoulders","core"}', 'other', 'core', 'duration'),
  ('Sled Push', 'quads', '{"glutes","core"}', 'machine', 'carry', 'distance_duration'),
  ('Sled Pull', 'quads', '{"back","core"}', 'machine', 'carry', 'distance_duration'),
  ('Medicine Ball Slam', 'core', '{"shoulders"}', 'other', 'core', 'reps_only'),
  ('Muscle-Up', 'back', '{"chest","triceps","shoulders"}', 'bodyweight', 'pull', 'reps_only'),
  ('Band Pull-Apart', 'shoulders', '{"back"}', 'band', 'pull', 'reps_only'),
  ('Band Bicep Curl', 'biceps', '{}', 'band', 'isolation', 'reps_only'),
  ('Band Lateral Raise', 'shoulders', '{}', 'band', 'isolation', 'reps_only'),
  ('Band Face Pull', 'shoulders', '{"back"}', 'band', 'pull', 'reps_only'),
  ('Band Squat', 'quads', '{"glutes"}', 'band', 'squat', 'reps_only'),
  ('Treadmill Run', 'fullBody', '{"legs"}', 'machine', 'carry', 'distance_duration'),
  ('Rowing Machine', 'back', '{"legs","arms","core"}', 'machine', 'pull', 'distance_duration'),
  ('Stationary Bike', 'quads', '{"hamstrings"}', 'machine', 'squat', 'distance_duration'),
  ('Elliptical', 'fullBody', '{"legs","arms"}', 'machine', 'carry', 'distance_duration'),
  ('Stair Climber', 'quads', '{"glutes","calves"}', 'machine', 'carry', 'duration'),
  ('Assault Bike', 'fullBody', '{"legs","arms"}', 'machine', 'carry', 'duration'),
  ('Jump Rope', 'calves', '{"shoulders"}', 'other', 'carry', 'duration')
;
    -- Backfill slug from name for the rows just inserted (normalized, lowercase, dash-joined).
    UPDATE exercises
    SET slug = trim(both '-' FROM regexp_replace(lower(name), '[^a-z0-9]+', '-', 'g'))
    WHERE is_custom = false AND slug IS NULL;

  END IF;
END $$;
